Replace pycodestyle with pep8 for python3 compatible
when runnig "ostestr cyborg.tests.unit.common.test_nova_client" under
py36, there throws the following error:
Failed to import test module: cyborg.tests.unit.test_hacking
  File "cyborg/tests/unit/test_hacking.py", line 18, in <module>
    import pep8
ImportError: No module named pep8

This is because pep8 doesn't exist any more in python3, pycodestyle is
the substitute.

Change-Id: Ia5bfa1f341606fc42b7a37a5fee9b426c59a05c2