Using pop method to avoid incompatible data type
Descrption:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'set' object does not support indexing

Solution:
for set, use pop method instead of index.

Change-Id: I33523ddb8aabf45eb11dd9816c52b0ef77d05296
(cherry picked from commit abe9f40fba0e11ee5549489b86fb5c23c83fdea4)