bug fix: endpoint register, import and devstack broken issues.
1. amend keyston endpoint register info
Service type should acceleration instead of cyborg.
For cyborg is just the service name.
We do not support uwsgi at present, so we must indicate service
port explicitly.

2. Fix package import error
Add full path to import module, so that the reference can be
resolved.

Story: 2001887
Task: 14368

3. devstack broken
TypeError: launch_service() got an unexpected keyword argument 'restart_method'
When initialize cyborg api service launcher, we already pass restart_method.
So no need to pass restart_method to launcher.launch_service, and it has not
restart_method argument.

Co-Authored-By: jiapei <jiapei2@lenovo.com>
Co-Authored-By: Zhipeng Huang <huangzhipeng@huawei.com>

Change-Id: Ic69e76b7bf86bbd1382aff07694ea9fbafd0862a