bug fix: fix 2 bugs for image client
1. missing glance config section

2. missing import keystoneauth1.exceptions
When call glance fail during download image, it will report:
 NameError: global name 'ks_exc' is not defined

Change-Id: I17f25368f3361b4fc20a0eda9d6b2788beaa6362